[project]
name = "comp-sec-project"
version = "0.1.0"
description = "Computer Security Final Project - Fall 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pycryptodome>=3.23.0",
    "pyyaml>=6.0.3",
]
